### ISSUE TITLE
给字体文件添加等宽信息

### ISSUE THREAD

**Issue by rexzhang** [lxgw/LxgwBright-Code#1]
以便支持字体管理使用「固定宽度」来搜索和过滤字体.很多软件在获取可用清单时也会依据这个做快速过滤
<img width="334" alt="截屏2024-09-21 23 52 19" src="https://github.com/user-attachments/assets/095c6a52-c52e-49a3-9082-5ab7f37f6c17">

**Comment by lxgw** [comment]
Mac OS 下不清楚，不过 Windows 下是能识别为等宽的。

**Comment by lxgw** [comment]
![image](https://github.com/user-attachments/assets/57f3348f-e455-4f16-98de-eecee48c955a)

Panose 信息也确实是等宽，所以并不知道问题出在了哪里。建议关闭「只显示等宽字体」的选项。

**Comment by lxgw** [comment]
文楷等宽版也有类似问题（lxgw/LxgwWenKai#101），无解。

**Comment by lxgw** [comment]
> 文楷等宽版也有类似问题（lxgw/LxgwWenKai#101），目前无解。

另外 macOS 对字体的分类也不够准确，比如它把「兰亭黑-繁」和 Arial Unicode MS 也识别成了等宽字体。

**Comment by rexzhang** [comment]
有可能macOS使用了一个特别的标识来识别等宽

**Comment by lxgw** [comment]
[LXGWBrightCodeGB.zip](https://github.com/user-attachments/files/17179849/LXGWBrightCodeGB.zip)

请问这个能否被识别？

**Comment by rexzhang** [comment]
> [LXGWBrightCodeGB.zip](https://github.com/user-attachments/files/17179849/LXGWBrightCodeGB.zip)
> 
> 请问这个能否被识别？

这个可以被识别到了
<img width="891" alt="截屏2024-09-30 11 24 01" src="https://github.com/user-attachments/assets/2db29a69-be5d-46cb-b55a-cf34a11242d7">
