### ISSUE TITLE
Fira Code?

### ISSUE THREAD

**Issue by PumpkinJui** [lxgw/LxgwBright-Code#2]
个人感觉 Monaspace 似乎棱角过多，还是和文楷不太融合……？
我之前用的是 [Fira Code](https://github.com/tonsky/FiraCode) 搭配的文楷，勉强作为参考。
不过，这也是我的*个人意见*，要不要改还是看大佬您的意见。

(注：我直接用手机上 MT 管理器内置的文本编辑器做的示例，Fira Code 的行间距不知道为什么很大……可能还需要您在其他设备上看看。)

Fira Code:

![Fira Code](https://github.com/user-attachments/assets/fc820f0c-9210-4dea-9ab4-65c159074f89)

Ysabeau (对照组):

![Ysabeau](https://github.com/user-attachments/assets/8ce20d63-8d7e-4bf5-800b-0ffa8a73a987)

Monaspace:

![Monaspace](https://github.com/user-attachments/assets/bc15342c-3af5-4005-b0c5-1b5e45877d90)

**Comment by lxgw** [comment]
个人觉得 Monaspace Argon 与 Ysabeau 风格上更相近，所以选择 Monaspace Argon 而不是 Fira Code / Fira Mono。您可以自行制作合并字体。

**Comment by Immortal-Sty** [comment]
想请教一下如何合并两种字体，并使其等宽呢？或者哪里有相关教程吗？
